/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelData {
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<crate::models::Channel>,
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<crate::models::ChannelMember>,
}

impl ChannelData {
    pub fn new() -> ChannelData {
        ChannelData {
            channel: None,
            member: None,
        }
    }
}


