/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct ChannelModerationPatch {
                    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
                    pub name: Option<String>,
                    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
                    pub roles: Option<crate::models::ChannelModeratedRolesPatch>,
                }

                impl ChannelModerationPatch {
                pub fn new() -> ChannelModerationPatch {
                ChannelModerationPatch {
                    name: None,
                    roles: None,
                }
                }
                }


