/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject14 {
    /// Mobile device id. For Android prefix the id with `android:` and Apple with `apple:`
    #[serde(rename = "device_id")]
    pub device_id: String,
}

impl InlineObject14 {
    pub fn new(device_id: String) -> InlineObject14 {
        InlineObject14 {
            device_id,
        }
    }
}


