/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject81 {
                        /// Trigger ID provided by other action
                    #[serde(rename = "trigger_id")]
                    pub trigger_id: String,
                        /// The URL to send the submitted dialog payload to
                    #[serde(rename = "url")]
                    pub url: String,
                    #[serde(rename = "dialog")]
                    pub dialog: crate::models::ActionsDialogsOpenDialog,
                }

                impl InlineObject81 {
                pub fn new(trigger_id: String, url: String, dialog: crate::models::ActionsDialogsOpenDialog) -> InlineObject81 {
                InlineObject81 {
                    trigger_id,
                    url,
                    dialog,
                }
                }
                }


