/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject68 {
                        /// The IDP certificate file
                    #[serde(rename = "certificate")]
                    pub certificate: std::path::PathBuf,
                }

                impl InlineObject68 {
                pub fn new(certificate: std::path::PathBuf) -> InlineObject68 {
                InlineObject68 {
                    certificate,
                }
                }
                }


