/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineResponse2002 {
                        /// Value will `true` if MFA is active, `false` otherwise
                    #[serde(rename = "mfa_required", skip_serializing_if = "Option::is_none", default, deserialize_with = "crate::de::parse_bool_opt")]
                    pub mfa_required: Option<bool>,
                }

                impl InlineResponse2002 {
                pub fn new() -> InlineResponse2002 {
                InlineResponse2002 {
                    mfa_required: None,
                }
                }
                }


