/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject33 {
                    #[serde(rename = "roles")]
                    pub roles: String,
                }

                impl InlineObject33 {
                pub fn new(roles: String) -> InlineObject33 {
                InlineObject33 {
                    roles,
                }
                }
                }


