/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject60 {
                        /// Number of users requested (20% extra is going to be added)
                    #[serde(rename = "users")]
                    pub users: i64,
                }

                impl InlineObject60 {
                pub fn new(users: i64) -> InlineObject60 {
                InlineObject60 {
                    users,
                }
                }
                }


