/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject6 {
                    #[serde(rename = "active", deserialize_with = "crate::de::parse_bool")]
                    pub active: bool,
                }

                impl InlineObject6 {
                pub fn new(active: bool) -> InlineObject6 {
                InlineObject6 {
                    active,
                }
                }
                }


