/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject87 {
                        /// A file to be uploaded
                    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
                    pub files: Option<std::path::PathBuf>,
                        /// The ID of the channel that this file will be uploaded to
                    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
                    pub channel_id: Option<String>,
                        /// A unique identifier for the file that will be returned in the response
                    #[serde(rename = "client_ids", skip_serializing_if = "Option::is_none")]
                    pub client_ids: Option<String>,
                }

                impl InlineObject87 {
                pub fn new() -> InlineObject87 {
                InlineObject87 {
                    files: None,
                    channel_id: None,
                    client_ids: None,
                }
                }
                }


