/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct InlineObject62 {
                        /// A file to be uploaded
                    #[serde(rename = "image")]
                    pub image: std::path::PathBuf,
                        /// A JSON object containing a `name` field with the name of the emoji and a `creator_id` field with the id of the authenticated user.
                    #[serde(rename = "emoji")]
                    pub emoji: String,
                }

                impl InlineObject62 {
                pub fn new(image: std::path::PathBuf, emoji: String) -> InlineObject62 {
                InlineObject62 {
                    image,
                    emoji,
                }
                }
                }


