/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct StatusOk {
                        /// Will contain \"ok\" if the request was successful and there was nothing else to return
                    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
                    pub status: Option<String>,
                }

                impl StatusOk {
                pub fn new() -> StatusOk {
                StatusOk {
                    status: None,
                }
                }
                }


