/*
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://openapi-generator.tech
 */




                #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
                pub struct UserAccessToken {
                        /// Unique identifier for the token
                    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
                    pub id: Option<String>,
                        /// The token used for authentication
                    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
                    pub token: Option<String>,
                        /// The user the token authenticates for
                    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
                    pub user_id: Option<String>,
                        /// A description of the token usage
                    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
                    pub description: Option<String>,
                }

                impl UserAccessToken {
                pub fn new() -> UserAccessToken {
                UserAccessToken {
                    id: None,
                    token: None,
                    user_id: None,
                    description: None,
                }
                }
                }


